apiVersion: kubevirtiphelper.k8s.binbash.org/v1
kind: IPPool
metadata:
  name: public-vlan1
spec:
  subnet: 10.135.10.0/24
  pool:
    start: 10.135.10.10
    end: 10.135.10.200
    exclude:
      - 10.135.10.150
      - 10.135.10.151
  router: 10.135.10.1
  dns:
    - 8.8.8.8
    - 4.4.4.4
  networkname: harvester-public/public-vlan-1
---
apiVersion: kubevirtiphelper.k8s.binbash.org/v1
kind: IPPool
metadata:
  name: public-vlan2
spec:
  subnet: 10.135.20.0/24
  pool:
    start: 10.135.20.10
    end: 10.135.20.200
    exclude:
      - 10.135.20.150
      - 10.135.20.151
  router: 10.135.20.1
  dns:
    - 8.8.8.8
    - 4.4.4.4
  networkname: harvester-public/public-vlan-2
---
apiVersion: kubevirtiphelper.k8s.binbash.org/v1
kind: IPReservation
metadata:
  name: test-vm1
spec:
  vmname: test-vm1
  ipreservations:
    - ipaddress: 10.135.10.195
      macaddress: 12:8b:a8:8c:da:11
      networkname: harvester-public/public-vlan-1
    - ipaddress: 10.135.20.201
      macaddress: aa:8b:a8:8c:da:cc
      networkname: harvester-public/public-vlan-2